# Copyright (c) 2018 The Harmonica Developers.
# Distributed under the terms of the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause
#
# This code is part of the Fatiando a Terra project (https://www.fatiando.org)
#
import datetime

import pygmt.sphinx_gallery
import pyvista
from sphinx_gallery.sorting import FileNameSortKey

import harmonica

# Project information
# -----------------------------------------------------------------------------
project = "Harmonica"
copyright_info = f"2018-{datetime.date.today().year}, The {project} Developers"
if len(harmonica.__version__.split("+")) > 1 or harmonica.__version__ == "unknown":
    version = "dev"
else:
    version = harmonica.__version__

# General configuration
# -----------------------------------------------------------------------------
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "numpydoc",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.doctest",
    "sphinx.ext.viewcode",
    "sphinx.ext.extlinks",
    "sphinx.ext.intersphinx",
    "sphinx_gallery.gen_gallery",
    "sphinx_design",
    "sphinx_copybutton",
    "jupyter_sphinx",
    "pyvista.ext.plot_directive",
]

# Configuration to include links to other project docs when referencing
# functions/classes
intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "numpy": ("https://docs.scipy.org/doc/numpy/", None),
    "numba": ("https://numba.pydata.org/numba-doc/latest/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/reference", None),
    "pandas": ("http://pandas.pydata.org/pandas-docs/stable/", None),
    "xarray": ("http://xarray.pydata.org/en/stable/", None),
    "xrft": ("https://xrft.readthedocs.io/en/stable/", None),
    "pooch": ("https://www.fatiando.org/pooch/latest/", None),
    "ensaio": ("https://www.fatiando.org/ensaio/latest/", None),
    "verde": ("https://www.fatiando.org/verde/latest/", None),
    "boule": ("https://www.fatiando.org/boule/latest/", None),
    "matplotlib": ("https://matplotlib.org/", None),
    "pyproj": ("https://pyproj4.github.io/pyproj/stable/", None),
    "pyvista": ("https://docs.pyvista.org", None),
    "numba_progress": (
        "https://pypi.org/project/numba-progress/",
        None,
    ),
    "pygmt": ("https://www.pygmt.org/latest/", None),
}

# Autosummary pages will be generated by sphinx-autogen instead of sphinx-build
autosummary_generate = []

# Create cross-references for the parameter types in the Parameters, Other
# Returns and Yields sections of the docstring
numpydoc_xref_param_type = True

# Format the Attributes section the Methods section and not like the Parameters
# section.
numpydoc_attributes_as_param_list = False

# Always show the source code that generates a plot
plot_include_source = True
plot_formats = ["png"]

# Sphinx project configuration
templates_path = ["_templates"]
exclude_patterns = ["_build", "**.ipynb_checkpoints"]
source_suffix = ".rst"
# The encoding of source files
source_encoding = "utf-8"
master_doc = "index"
pygments_style = "default"
add_function_parentheses = False


# Sphinx-Gallery configuration
# -----------------------------------------------------------------------------
sphinx_gallery_conf = {
    # path to your examples scripts
    "examples_dirs": ["../examples"],
    # path where to save gallery generated examples
    "gallery_dirs": ["gallery"],
    "filename_pattern": r"\.py",
    # Remove the "Download all examples" button from the top level gallery
    "download_all_examples": False,
    # Sort gallery example by file name instead of number of lines (default)
    "within_subsection_order": FileNameSortKey,
    # directory where function granular galleries are stored
    "backreferences_dir": "api/generated/backreferences",
    # Modules for which function level galleries are created.  In
    # this case sphinx_gallery and numpy in a tuple of strings.
    "doc_module": "harmonica",
    # Insert links to documentation of objects in the examples
    "reference_url": {"harmonica": None},
    # Add pyvista to the image scrapers
    "image_scrapers": (
        "pyvista",
        "matplotlib",
        pygmt.sphinx_gallery.PyGMTScraper(),
    ),
}


# Pyvista configurations
# -----------------------------------------------------------------------------
# necessary when building the sphinx gallery
pyvista.BUILDING_GALLERY = True
pyvista.OFF_SCREEN = True

# Optional - set parameters like theme or window size
pyvista.set_plot_theme("document")
pyvista.global_theme.window_size = (1024 * 2, 768 * 2)


# HTML output configuration
# -----------------------------------------------------------------------------
html_title = f'{project} <span class="project-version">{version}</span>'
# Don't use the logo since it gets in the way of the project name and is
# repeated in the front page.
# html_logo = "_static/harmonica-logo.png"
html_favicon = "_static/favicon.png"
html_last_updated_fmt = "%b %d, %Y"
html_copy_source = True
html_static_path = ["_static"]
# CSS files are relative to the static path
html_css_files = ["custom.css"]
html_extra_path = []
html_show_sourcelink = False
html_show_sphinx = True
html_show_copyright = True

html_theme = "sphinx_book_theme"
html_theme_options = {
    "repository_url": "https://github.com/fatiando/harmonica",
    "repository_branch": "main",
    "path_to_docs": "doc",
    "launch_buttons": {
        "binderhub_url": "https://mybinder.org",
        "notebook_interface": "jupyterlab",
    },
    "use_edit_page_button": True,
    "use_issues_button": True,
    "use_repository_button": True,
    "use_download_button": True,
    "home_page_in_toc": False,
}
