"""
Normal gravity calculation
==========================

Gravitational disturbances allows geoscientists to infer the internal structure
of the Earth. In order to compute a gravitational disturbance, we must define
a normal gravity.
Usually, the normal gravity is defined as the gravitational effect of the
reference ellipsoid. [LiGotze2001]_ introduced a closed-form formula to compute
the magntiude of the gradient of the gravitational potential generated by any
reference ellipsoid.
The :func:`harmonica.normal_gravity` function uses this closed-form formula to
compute the gravitational effect of the reference ellipsoid given by
:func:`harmonica.set_ellipsoid`.
"""
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import harmonica as hm
import verde as vd

# Create a computation grid
region = [0, 360, -90, 90]
lon, lat = vd.grid_coordinates(region, spacing=1.0)

# Compute the gravitational effect of the WGS84 (default) ellipsoid
# on its surface
gamma = hm.normal_gravity(latitude=lat, height=0)

# Make a plot of the normal gravity using Cartopy
plt.figure(figsize=(6, 3))
ax = plt.axes(projection=ccrs.Mollweide())
ax.set_title("Normal gravity on the ellipsoid WGS84")
ax.coastlines()
plt.contourf(lon, lat, gamma, 150, transform=ccrs.PlateCarree())
plt.colorbar(label="mGal")
plt.tight_layout()
plt.show()
