# Build the documentation to check that it works without errors.
#
# NOTE: Pin actions to a specific commit to avoid having the authentication
# token stolen if the Action is compromised. See the comments and links here:
# https://github.com/pypa/gh-action-pypi-publish/issues/27
#
name: documentation

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

# Use bash by default in all jobs
defaults:
  run:
    # The -l {0} is necessary for conda environments to be activated
    # But this breaks on MacOS if using actions/setup-python:
    # https://github.com/actions/setup-python/issues/132
    # -e makes sure builds fail if any command fails
    shell: bash -e -o pipefail -l {0}

jobs:
  #############################################################################
  # Build the docs
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON: "3.12"
      ENSAIO_DATA_FROM_GITHUB: true

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # Need to fetch more than the last commit so that setuptools-scm can
          # create the correct version string. If the number of commits since
          # the last release is greater than this, the version still be wrong.
          # Increase if necessary.
          fetch-depth: 100
          # The GitHub token is preserved by default but this job doesn't need
          # to be able to push to GitHub.
          persist-credentials: false

      # Need the tags so that setuptools-scm can form a valid version number
      - name: Fetch git tags
        run: git fetch origin 'refs/tags/*:refs/tags/*'

      - name: Setup caching for conda packages
        uses: actions/cache@v5
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ env.PYTHON }}-${{ hashFiles('.github/environment.yml') }}

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@fc2d68f6413eb2d87b895e92f8584b5b94a10167
        with:
          python-version: ${{ env.PYTHON }}
          miniforge-version: latest
          channels: conda-forge
          conda-remove-defaults: "true"
          activate-environment: harmonica-docs
          environment-file: .github/environment.yml

      - name: List installed packages
        run: conda list

      - name: Build source and wheel distributions
        run: make build

      - name: Install the package
        run: python -m pip install --no-deps dist/*.whl

      - name: Build the documentation
        run: |
          # Install xvfb and run some commands to allow pyvista to run on
          # a headless system.
          sudo apt-get install xvfb
          export DISPLAY=:99.0
          export PYVISTA_OFF_SCREEN=true
          export PYVISTA_USE_IPYVTK=true
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 3
          # Build the docs
          make -C doc clean all
